spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  datasource:
    password:
    username:
    url: jdbc:postgresql://localhost:5432/postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/spring
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: off
  cloud:
    aws:
      region:
        static: eu-central-1
      endpoint: http://localhost:9324
      credentials:
        secret-key:
        access-key:
  jackson:
    default-property-inclusion: non_null

clients:
  open-library:
    base-url: https://openlibrary.org

sqs:
  book-synchronization-queue: default
